# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ebe445c538a48003d2474430e74358e36e2de90224d1d2430cace9e82e11070f8e89dc329c11953e9f3a2396af84c2abaef4600b007526cc954b698cdc7aedc

test:
  secret_key_base: 1fb62c1f55219829734d14d92d33ab84ffb8e1caedafe5a6b0b27ea74a4a3eeed80843fdee31be102f5bd58603e884d61f5600666776a6fc682133b41c27e583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
